<?php

/**
 * Ztl SVG list
 *
 * @package Autoresq
 */
class Ztl_Images
{
    public $images = array(
        array('ztl-icon-ac-car-airconditioner-air-circulation-fan-accessories' => 'AC Air Conditioning Fan'),
        array('ztl-icon-air-conditioning-ac-cold-automobile-part-car' => 'AC Air Conditioning Part'),
        array('ztl-icon-airplane-service-shipment-shipping-logistic-delivery' => 'Airplane Service'),
        array('ztl-icon-aliment-wheel-automobile-part-car' => 'Aliment Wheels'),
        array('ztl-icon-analysis-graph-packing-shipment-shipping-logistic-delivery' => 'Analysis Graph Packing'),
        array('ztl-icon-arrow-packing-service-shipment-shipping-logistic-delivery' => 'Arrow Packing'),
        array('ztl-icon-barcode-packing-service-shipment-shipping-logistic-delivery' => 'Barcode Packing'),
        array('ztl-icon-battery-automobile-part-car' => 'Battery Automobile'),
        array('ztl-icon-battery-clamper-car-accessories-starter-power' => 'Battery Clamper'),
        array('ztl-icon-body-paint-repair-color-maintenance-service' => 'Body Paint Repair'),
        array('ztl-icon-box-packing-service-shipment-shipping-logistic-delivery' => 'Box Packing Service'),
        array('ztl-icon-box-packing-service-shipment-shipping-logistic-delivery-1' => 'Box Packing Service 1'),
        array('ztl-icon-broken-packing-service-shipment-shipping-logistic-delivery' => 'Broken Packing Service'),
        array('ztl-icon-bus-vehicle-automobile-transport' => 'Bus Vehicle'),
        array('ztl-icon-calculator-service-shipment-shipping-logistic-delivery' => 'Calculator Service Shipment'),
        array('ztl-icon-calendar-packing-service-shipment-shipping-logistic-delivery' => 'Calendar Packing'),
        array('ztl-icon-callcenter-human-service-shipment-shipping-logistic-delivery' => 'Call Center Human'),
        array('ztl-icon-caption-packing-service-shipment-shipping-logistic-delivery' => 'Caption'),
        array('ztl-icon-car-door-mirror-automobile-lock' => 'Car Door Mirror'),
        array('ztl-icon-car-wash-clean-service-automobile' => 'Car Wash Clean'),
        array('ztl-icon-card-credit-money-shipment-shipping-logistic-delivery' => 'Card Credit Money'),
        array('ztl-icon-cargo-packing-service-shipment-shipping-logistic-delivery' => 'Cargo Packing Service'),
        array('ztl-icon-carservice-car-repair-service-servicestation-garage' => 'Car Service'),
        array('ztl-icon-cartrunk-trunk-service-damage-maintanance' => 'Car Trunk'),
        array('ztl-icon-certification-packing-service-shipment-shipping-logistic-delivery' => 'Certification Service'),
        array('ztl-icon-clock-time-packing-shipment-shipping-logistic-delivery' => 'Clock Time'),
        array('ztl-icon-cogwheel-gear-gears-engine-mechamism' => 'Cogwheel Gear'),
        array('ztl-icon-compass-map-navigation-road-gps-tracing' => 'Compass Navigation'),
        array('ztl-icon-computer-website-service-shipment-shipping-logistic-delivery' => 'Computer Website Service'),
        array('ztl-icon-container-service-shipment-shipping-logistic-delivery' => 'Container Shipment'),
        array('ztl-icon-cool-air-circulation-comfort' => 'Cool Air Circulation'),
        array('ztl-icon-counter-packing-service-shipment-shipping-logistic-delivery' => 'Counter Packing Service'),
        array('ztl-icon-diagnostic-monitoring-system-car-analysis' => 'Diagnostic Monitoring'),
        array('ztl-icon-disc-brake-automobile-part-car' => 'Disc Brake'),
        array('ztl-icon-drone-packing-service-shipment-shipping-logistic-delivery' => 'Drone Packing'),
        array('ztl-icon-ecommerce-packing-service-shipment-shipping-logistic-delivery' => 'Ecommerce Packing'),
        array('ztl-icon-ecommerce-packing-service-shipment-shipping-logistic-delivery-1' => 'Ecommerce Packing 1'),
        array('ztl-icon-ecommerce-packing-service-shipment-shipping-logistic-delivery-1-2' => 'Ecommerce Packing 2'),
        array('ztl-icon-ecommerce-packing-service-shipment-shipping-logistic-delivery-1-2-3' => 'Ecommerce Packing 3'),
        array('ztl-icon-ecommerce-service-shipment-shipping-logistic-delivery' => 'Ecommerce Service'),
        array('ztl-icon-ecommerce-service-shipment-shipping-logistic-delivery-1' => 'Ecommerce Service 1'),
        array('ztl-icon-ecommerce-shopping-service-shipment-shipping-logistic-delivery' => 'Ecommerce Shopping'),
        array('ztl-icon-electrical-service-tool-automobile-car-repair' => 'Electrical Service'),
        array('ztl-icon-engine-oil-automobile-part-car-fuel' => 'Engine Oil'),
        array('ztl-icon-engine-turnup-automobile-part-car' => 'Engine Turnup'),
        array('ztl-icon-exhaust-automobile-part-car' => 'Exhaust Automobile'),
        array('ztl-icon-fan-exhuast-air-circulation-recycle' => 'Fan Exhuast Air'),
        array('ztl-icon-fire-safety-extinguisher-warning-protection-safe' => 'Fire Safety Extinguisher'),
        array('ztl-icon-fire-smoke-automobile' => 'Fire Smoke'),
        array('ztl-icon-flag-packing-service-shipment-shipping-logistic-delivery' => 'Flag'),
        array('ztl-icon-folklife-packing-service-shipment-shipping-logistic-delivery' => 'Folk Life'),
        array('ztl-icon-free-packing-service-shipment-shipping-logistic-delivery' => 'Free Packing Service'),
        array('ztl-icon-fuel-petrol-gas-gasoline-consumption-station' => 'Fuel Petrol Gas'),
        array('ztl-icon-gear-manual-transmission-car-gearbox-automobile-vehicle' => 'Gear Manual Transmission'),
        array('ztl-icon-gear-mechanism-automobile-part-car' => 'Gear Mechanism Automobile'),
        array('ztl-icon-gps-location-smartphone-shipment-shipping-logistic-delivery' => 'GPS Location Smart Phone'),
        array('ztl-icon-gps-packing-service-shipment-shipping-logistic-delivery' => 'GPS Packing Service'),
        array('ztl-icon-gps-packing-service-shipment-shipping-logistic-delivery-1' => 'GPS Packing Service 1'),
        array('ztl-icon-gps-service-shipment-shipping-logistic-delivery' => 'GPS Service'),
        array('ztl-icon-graph-packing-service-shipment-shipping-logistic-delivery' => 'Graph Packing Service'),
        array('ztl-icon-greece-oil-bottle-maintanance-mechanic-service' => 'Greece Oil Bottle'),
        array('ztl-icon-horn-blow-carhorn-vehicle-traffic' => 'Horn Blow Car Horn'),
        array('ztl-icon-human-packing-service-shipment-shipping-logistic-delivery' => 'Human Packing Service'),
        array('ztl-icon-ignition-spark-plug-automobile-part-car' => 'Ignition Spark Plug'),
        array('ztl-icon-inflate-tire-air-pressure-check-measure' => 'Inflate Tire Air'),
        array('ztl-icon-key-remote-control-lock-unlock-car' => 'Key Remote Control'),
        array('ztl-icon-like-packing-service-shipment-shipping-logistic-delivery' => 'Like'),
        array('ztl-icon-location-service-shipment-shipping-logistic-delivery' => 'Location'),
        array('ztl-icon-mag-wheel-rim-automobile-part-car' => 'Mag Wheel Rim'),
        array('ztl-icon-magnify-service-shipment-shipping-logistic-delivery' => 'Magnify Service Shipment'),
        array('ztl-icon-maintenance-repair-service-car-automobile' => 'Maintenance Repair Service'),
        array('ztl-icon-meter-power-energy-automobile-part-car' => 'Meter Power Energy'),
        array('ztl-icon-money-shopping-service-shipment-shipping-logistic-delivery' => 'Money Shopping Service'),
        array('ztl-icon-motorcycle-packing-service-shipment-shipping-logistic-delivery' => 'Motorcycle'),
        array('ztl-icon-painting-work-color-gun-spray-tool' => 'Painting Work Color'),
        array('ztl-icon-parachute-packing-service-shipment-shipping-logistic-delivery' => 'Parachute'),
        array('ztl-icon-phone-mobile-telephone-emergency-walky-talky' => 'Phone Mobile'),
        array('ztl-icon-piston-automobile-part-car' => 'Piston Automobile Part'),
        array('ztl-icon-process-packing-service-shipment-shipping-logistic-delivery' => 'Process Packing'),
        array('ztl-icon-process-packing-service-shipment-shipping-logistic-delivery-1' => 'Process Packing 1'),
        array('ztl-icon-protect-packing-service-shipment-shipping-logistic-delivery' => 'Protect Packing Service'),
        array('ztl-icon-protect-security-service-shipment-shipping-logistic-delivery' => 'Protect Security'),
        array('ztl-icon-radiator-automobile-part-car' => 'Radiator Automobile Part'),
        array('ztl-icon-refuel-car-vehicle-service-automobile-transport' => 'Refuel Car Vehicle'),
        array('ztl-icon-remote-keyless-system-automatic' => 'Remote Keyless System'),
        array('ztl-icon-report-packing-service-shipment-shipping-logistic-delivery' => 'Report Service'),
        array('ztl-icon-report-packing-service-shipment-shipping-logistic-delivery-1' => 'Report Service'),
        array('ztl-icon-rims-tire-accessoties-wheel-automobile' => 'Rims Tire Accessories'),
        array('ztl-icon-rims-tire-accessoties-wheel-automobile-car' => 'Rims Tire Accessories'),
        array('ztl-icon-rocket-packing-service-shipment-shipping-logistic-delivery' => 'Rocket Packing Service'),
        array('ztl-icon-safety-belt-seatbelt-security-protectionaccessories' => 'Safety Belt Seat Belt'),
        array('ztl-icon-scale-packing-service-shipment-shipping-logistic-delivery' => 'Scale'),
        array('ztl-icon-seat-driver-chair-frontseat-accessories-automobile' => 'Seat Driver Chair'),
        array('ztl-icon-shop-packing-service-shipment-shipping-logistic-delivery' => 'Shop Service'),
        array('ztl-icon-shopping-packing-service-shipment-shipping-logistic-delivery' => 'Shopping Service'),
        array('ztl-icon-sidemirror-mirror-glass-car-automobile' => 'Sidemirror Mirror Glass'),
        array('ztl-icon-silencer-exhaust-pollution-controller-accessories-car' => 'Silencer Exhaust Pollution'),
        array('ztl-icon-sound-speaker-hoofer-music-accessories' => 'Sound Speaker Hoofer'),
        array('ztl-icon-spanner-wrench-screwdriver-tool-repair-service-maintanace' => 'Spanner Wrench Screwdriver'),
        array('ztl-icon-speed-transport-vehicle-service-shipping-logistic-delivery' => 'Speed Transport Vehicle'),
        array('ztl-icon-speedometer-indicator-dashboard-rpm-odometer-speed' => 'Speedometer Indicator Dashboard'),
        array('ztl-icon-state-inpecion-check-list-service-automobile-car' => 'State Inspection Check'),
        array('ztl-icon-steering-wheel-automobile-part-car' => 'Steering Wheel Automobile'),
        array('ztl-icon-strut-suspension-automobile-parts-spring-car-service' => 'Strut Suspension Automobile'),
        array('ztl-icon-suspension-lift-carry-up-service-maintenance' => 'Suspension Lift Carry'),
        array('ztl-icon-technician-avatar-mechanic-car' => 'Technician Avatar Mechanic'),
        array('ztl-icon-tire-wheel-automobile-part-car' => 'Tire Wheel Automobile'),
        array('ztl-icon-trailer-car-load-carry-automobile-part' => 'Trailer Car Load'),
        array('ztl-icon-transport-packing-service-shipment-shipping-logistic-delivery' => 'Transport Packing Service'),
        array('ztl-icon-transport-packing-service-shipment-shipping-logistic-delivery-1' => 'Transport Packing Service 1'),
        array('ztl-icon-transport-packing-service-shipment-shipping-logistic-delivery-1-2' => 'Transport Packing Service 2'),
        array('ztl-icon-transport-packing-service-shipment-shipping-logistic-delivery-1-2-3' => 'Transport Packing Service 3'),
        array('ztl-icon-transport-vehicle-service-shipment-shipping-logistic-delivery' => 'Transport Vehicle Service'),
        array('ztl-icon-viper-frontglass-wash-windshield-cleaner-accessories-carservice' => 'Viper Front Glass Wash'),
        array('ztl-icon-warehouse-packing-service-shipment-shipping-logistic-delivery' => 'Warehouse Packing Service'),
        array('ztl-icon-warehouse-packing-service-shipment-shipping-logistic-delivery-1' => 'Warehouse Packing Service'),
        array('ztl-icon-wind-pump-station-automobile-service' => 'Wind Pump Station'),
        array('ztl-icon-wiper-wash-clean-glass-automobile-car' => 'Wiper Wash Clean'),
        array('ztl-icon-wrenching-wrench-screwdriver-repair-fitting-fix' => 'Wrenching Wrench Screwdriver'),
	    array('ztl-icon-001-car-parts-4'=>'Car Parts'),
	    array('ztl-icon-002-elevator'=>'Car Elevator'),
	    array('ztl-icon-003-car-parts-3'=>'Car Parts'),
	    array('ztl-icon-004-car-parts-2'=>'Car Parts'),
	    array('ztl-icon-005-car-parts-1'=>'Car Parts'),
	    array('ztl-icon-006-car-parts'=>'Car Parts'),
	    array('ztl-icon-007-settings-2'=>'Car Chip Settings'),
	    array('ztl-icon-008-mail'=>'Email'),
	    array('ztl-icon-009-email'=>'Email'),
	    array('ztl-icon-010-machine-1'=>'Machine'),
	    array('ztl-icon-011-tools'=>'Car Tools'),
	    array('ztl-icon-012-car'=>'Car'),
	    array('ztl-icon-013-mechanic-5'=>'Car Mechanic'),
	    array('ztl-icon-014-oil'=>'Car Oil'),
	    array('ztl-icon-015-cogwheels'=>'Car Cogwheels'),
	    array('ztl-icon-016-pistons-1'=>'Car Pistons'),
	    array('ztl-icon-017-mechanic-4'=>'Car Mechanic'),
	    array('ztl-icon-018-car-repair'=>'Car Repair'),
	    array('ztl-icon-019-engine'=>'Car Engine'),
	    array('ztl-icon-020-machine'=>'Machine'),
	    array('ztl-icon-021-robotic-arm'=>'Car Robotic Arm'),
	    array('ztl-icon-022-mechanic-3'=>'Car Mechanic'),
	    array('ztl-icon-023-plan'=>'Car Plan'),
	    array('ztl-icon-024-pistons'=>'Car Pistons'),
	    array('ztl-icon-025-gauge'=>'Car Gauge'),
	    array('ztl-icon-026-mechanic-2'=>'Car Mechanic'),
	    array('ztl-icon-027-settings'=>'Car Settings'),
	    array('ztl-icon-028-mechanic-1'=>'Car Mechanic'),
	    array('ztl-icon-029-mechanic'=>'Car Mechanic'),
	    array('ztl-icon-030-settings-1'=>'Car Settings'),
	    array('ztl-icon-clock'=>'Clock'),

    );

    /**
     * @return array
     */
    public function getAll(){
        return $this->images;
    }

    public function getLocation(){
        return dirname(__FILE__).'/../shortcodes/assets/svg/';
    }


}