<?php
/**
 * Theme Framework
 */

if( !defined( 'ABSPATH' ) ) exit; // Exit if accessed directly


/**
 * [yog_attributes_head description]
 * @method yog_attributes_head
 * @param  [type]                $attributes [description]
 * @return [type]                            [description]
 */
add_filter( 'yog_attr_head', 'yog_attributes_head' );
function yog_attributes_head( $attributes ) {

	unset( $attributes['class'] );
	if ( ! is_front_page() ) {
		return $attributes;
	}

	$attributes['itemscope'] = 'itemscope';
	$attributes['itemtype']  = 'http://schema.org/WebSite';

	return $attributes;
}

/**
 * [yog_attributes_body description]
 * @method yog_attributes_body
 * @param  [type]                $attributes [description]
 * @return [type]                            [description]
 */
add_filter( 'yog_attr_body', 'yog_attributes_body' );
function yog_attributes_body( $attributes ) {

	$attributes['class']     = join( ' ', get_body_class() );
	$attributes['dir']       = is_rtl() ? 'rtl' : 'ltr';
	$attributes['itemscope'] = 'itemscope';
	$attributes['itemtype']  = 'http://schema.org/WebPage';

	if ( is_singular( 'post' ) || is_home() || is_archive() ) {
		$attributes['itemtype'] = 'http://schema.org/Blog';
	}

	if ( is_search() ) {
		$attributes['itemtype'] = 'http://schema.org/SearchResultsPage';
	}

	return $attributes;
}

/**
 * [yog_attributes_content description]
 * @method yog_attributes_content
 * @param  [type]                   $attributes [description]
 * @return [type]                               [description]
 */
add_filter( 'yog_attr_content', 'yog_attributes_content' );
function yog_attributes_content( $attributes ) {

	$attributes['id'] = 'content';

	return $attributes;

}

/**
 * [yog_get_logo description]
 * @method yog_get_logo
 * @return [type]             [description]
 */
function yog_get_logo( $yog_args = '' ) {
    
   $yog_defaults = array(
        'yog_container'       => 'div',
        'yog_container_class' => 'logo',
        'yog_alt'             => get_bloginfo( 'name' ),
        'yog_title'           => get_bloginfo( 'name' ),
        'yog_link_class'      => 'navbar-brand',
        'yog_logo_class'      => false,
        'yog_logo'            => yog_helper()->get_option( 'opt-logo' ),
    );
    $yog_args = wp_parse_args( $yog_args, $yog_defaults );
    extract( $yog_args, EXTR_SKIP );
    
    //Logo Container.
    $yog_before = $yog_after = '';
    if( !empty( $yog_container ) ){
        $yog_before = sprintf( '<%1$s class="%2$s">', esc_attr( $yog_container ), esc_attr( $yog_container_class )  );
        $yog_after = sprintf( '</%1$s>', esc_attr( $yog_container ) );
    }
     
    //Get Logo Html
    if( isset( $yog_logo['url'] ) && !empty( $yog_logo['url'] ) ){
        $yog_link = sprintf( '<a class="%1$s" href="%2$s" title="%4$s"><img src="%3$s" alt="%4$s" %5$s></a>',esc_attr( $yog_link_class ), esc_url( home_url( '/' ) ), esc_url( $yog_logo['url'] ), esc_attr( $yog_alt ), ( $yog_logo_class )? 'class="'. esc_attr( $yog_logo_class ) .'"' : '' );
    }else{
        $yog_link = sprintf( '<a class="%1$s" href="%2$s" title="%3$s">%3$s</a>',esc_attr( $yog_link_class ), esc_url( home_url( '/' ) ), esc_html( $yog_title ) );
    }
    
    //Return Logo Html
    return $yog_before . $yog_link . $yog_after;
}

/**
 * [yog_get_options_fontawesome_icons description]
 * @method yog_get_options_fontawesome_icons
 * @return [type]                     [description]
 */
function yog_get_options_fontawesome_icons(){
    
     return array(
        'fa-adjust' => esc_html__( 'Adjust', 'flipmart' ),
        'fa-adn' => esc_html__( 'Adn', 'flipmart' ),
        'fa-align-center' => esc_html__( 'Align Center', 'flipmart' ),
        'fa-align-justify' => esc_html__( 'Align Justify', 'flipmart' ),
        'fa-align-left' => esc_html__( 'Align Left', 'flipmart' ),
        'fa-align-right' => esc_html__( 'Align Right', 'flipmart' ),
        'fa-ambulance' => esc_html__( 'Ambulance', 'flipmart' ),
        'fa-anchor' => esc_html__( 'Anchor', 'flipmart' ),
        'fa-android' => esc_html__( 'Android', 'flipmart' ),
        'fa-angellist' => esc_html__( 'Angellist', 'flipmart' ),
        'fa-angle-double-down' => esc_html__( 'Angle Double Down', 'flipmart' ),
        'fa-angle-double-left' => esc_html__( 'Angle Double Left', 'flipmart' ),
        'fa-angle-double-right' => esc_html__( 'Angle Double Right', 'flipmart' ),
        'fa-angle-double-up' => esc_html__( 'Angle Double Up', 'flipmart' ),
        'fa-angle-down' => esc_html__( 'Angle Down', 'flipmart' ),
        'fa-angle-left' => esc_html__( 'Angle Left', 'flipmart' ),
        'fa-angle-right' => esc_html__( 'Angle Right', 'flipmart' ),
        'fa-angle-up' => esc_html__( 'Angle Up', 'flipmart' ),
        'fa-apple' => esc_html__( 'Apple', 'flipmart' ),
        'fa-archive' => esc_html__( 'Archive', 'flipmart' ),
        'fa-area-chart' => esc_html__( 'Area Chart', 'flipmart' ),
        'fa-arrow-circle-down' => esc_html__( 'Arrow Circle Down', 'flipmart' ),
        'fa-arrow-circle-left' => esc_html__( 'Arrow Circle Left', 'flipmart' ),
        'fa-arrow-circle-o-down' => esc_html__( 'Arrow Circle Outline Down', 'flipmart' ),
        'fa-arrow-circle-o-left' => esc_html__( 'Arrow Circle Outline Left', 'flipmart' ),
        'fa-arrow-circle-o-right' => esc_html__( 'Arrow Circle Outline Right', 'flipmart' ),
        'fa-arrow-circle-o-up' => esc_html__( 'Arrow Circle Outline Up', 'flipmart' ),
        'fa-arrow-circle-right' => esc_html__( 'Arrow Circle Right', 'flipmart' ),
        'fa-arrow-circle-up' => esc_html__( 'Arrow Circle Up', 'flipmart' ),
        'fa-arrow-down' => esc_html__( 'Arrow Down', 'flipmart' ),
        'fa-arrow-left' => esc_html__( 'Arrow Left', 'flipmart' ),
        'fa-arrow-right' => esc_html__( 'Arrow Right', 'flipmart' ),
        'fa-arrow-up' => esc_html__( 'Arrow Up', 'flipmart' ),
        'fa-arrows-alt' => esc_html__( 'Arrows Alt', 'flipmart' ),
        'fa-arrows-h' => esc_html__( 'Arrows H', 'flipmart' ),
        'fa-arrows-v' => esc_html__( 'Arrows V', 'flipmart' ),
        'fa-arrows' => esc_html__( 'Arrows', 'flipmart' ),
        'fa-asterisk' => esc_html__( 'Asterisk', 'flipmart' ),
        'fa-at' => esc_html__( 'At', 'flipmart' ),
        'fa-automobile' => esc_html__( 'Automobile', 'flipmart' ),
        'fa-backward' => esc_html__( 'Backward', 'flipmart' ),
        'fa-ban' => esc_html__( 'Ban', 'flipmart' ),
        'fa-bank' => esc_html__( 'Bank', 'flipmart' ),
        'fa-bar-chart-o' => esc_html__( 'Bar Chart Outline', 'flipmart' ),
        'fa-bar-chart' => esc_html__( 'Bar Chart', 'flipmart' ),
        'fa-barcode' => esc_html__( 'Barcode', 'flipmart' ),
        'fa-bars' => esc_html__( 'Bars', 'flipmart' ),
        'fa-beer' => esc_html__( 'Beer', 'flipmart' ),
        'fa-behance-square' => esc_html__( 'Behance Square', 'flipmart' ),
        'fa-behance' => esc_html__( 'Behance', 'flipmart' ),
        'fa-bell-o' => esc_html__( 'Bell Outline', 'flipmart' ),
        'fa-bell-slash-o' => esc_html__( 'Bell Slash Outline', 'flipmart' ),
        'fa-bell-slash' => esc_html__( 'Bell Slash', 'flipmart' ),
        'fa-bell' => esc_html__( 'Bell', 'flipmart' ),
        'fa-bicycle' => esc_html__( 'Bicycle', 'flipmart' ),
        'fa-binoculars' => esc_html__( 'Binoculars', 'flipmart' ),
        'fa-birthday-cake' => esc_html__( 'Birthday Cake', 'flipmart' ),
        'fa-bitbucket-square' => esc_html__( 'Bitbucket Square', 'flipmart' ),
        'fa-bitbucket' => esc_html__( 'Bitbucket', 'flipmart' ),
        'fa-bitcoin' => esc_html__( 'Bitcoin', 'flipmart' ),
        'fa-bold' => esc_html__( 'Bold', 'flipmart' ),
        'fa-bolt' => esc_html__( 'Bolt', 'flipmart' ),
        'fa-bomb' => esc_html__( 'Bomb', 'flipmart' ),
        'fa-book' => esc_html__( 'Book', 'flipmart' ),
        'fa-bookmark-o' => esc_html__( 'Bookmark Outline', 'flipmart' ),
        'fa-bookmark' => esc_html__( 'Bookmark', 'flipmart' ),
        'fa-briefcase' => esc_html__( 'Briefcase', 'flipmart' ),
        'fa-btc' => esc_html__( 'Btc', 'flipmart' ),
        'fa-bug' => esc_html__( 'Bug', 'flipmart' ),
        'fa-building-o' => esc_html__( 'Building Outline', 'flipmart' ),
        'fa-building' => esc_html__( 'Building', 'flipmart' ),
        'fa-bullhorn' => esc_html__( 'Bullhorn', 'flipmart' ),
        'fa-bullseye' => esc_html__( 'Bullseye', 'flipmart' ),
        'fa-bus' => esc_html__( 'Bus', 'flipmart' ),
        'fa-cc-amex' => esc_html__( 'CC Amex', 'flipmart' ),
        'fa-cc-discover' => esc_html__( 'CC Discover', 'flipmart' ),
        'fa-cc-mastercard' => esc_html__( 'CC Mastercard', 'flipmart' ),
        'fa-cc-paypal' => esc_html__( 'CC Paypal', 'flipmart' ),
        'fa-cc-stripe' => esc_html__( 'CC Stripe', 'flipmart' ),
        'fa-cc-visa' => esc_html__( 'CC Visa', 'flipmart' ),
        'fa-cab' => esc_html__( 'Cab', 'flipmart' ),
        'fa-calculator' => esc_html__( 'Calculator', 'flipmart' ),
        'fa-calendar-o' => esc_html__( 'Calendar Outline', 'flipmart' ),
        'fa-calendar' => esc_html__( 'Calendar', 'flipmart' ),
        'fa-camera-retro' => esc_html__( 'Camera Retro', 'flipmart' ),
        'fa-camera' => esc_html__( 'Camera', 'flipmart' ),
        'fa-car' => esc_html__( 'Car', 'flipmart' ),
        'fa-caret-down' => esc_html__( 'Caret Down', 'flipmart' ),
        'fa-caret-left' => esc_html__( 'Caret Left', 'flipmart' ),
        'fa-caret-right' => esc_html__( 'Caret Right', 'flipmart' ),
        'fa-caret-square-o-down' => esc_html__( 'Caret Square Outline Down', 'flipmart' ),
        'fa-caret-square-o-left' => esc_html__( 'Caret Square Outline Left', 'flipmart' ),
        'fa-caret-square-o-right' => esc_html__( 'Caret Square Outline Right', 'flipmart' ),
        'fa-caret-square-o-up' => esc_html__( 'Caret Square Outline Up', 'flipmart' ),
        'fa-caret-up' => esc_html__( 'Caret Up', 'flipmart' ),
        'fa-cc' => esc_html__( 'Cc', 'flipmart' ),
        'fa-certificate' => esc_html__( 'Certificate', 'flipmart' ),
        'fa-chain-broken' => esc_html__( 'Chain Broken', 'flipmart' ),
        'fa-chain' => esc_html__( 'Chain', 'flipmart' ),
        'fa-check-circle-o' => esc_html__( 'Check Circle Outline', 'flipmart' ),
        'fa-check-circle' => esc_html__( 'Check Circle', 'flipmart' ),
        'fa-check-square-o' => esc_html__( 'Check Square Outline', 'flipmart' ),
        'fa-check-square' => esc_html__( 'Check Square', 'flipmart' ),
        'fa-check' => esc_html__( 'Check', 'flipmart' ),
        'fa-chevron-circle-down' => esc_html__( 'Chevron Circle Down', 'flipmart' ),
        'fa-chevron-circle-left' => esc_html__( 'Chevron Circle Left', 'flipmart' ),
        'fa-chevron-circle-right' => esc_html__( 'Chevron Circle Right', 'flipmart' ),
        'fa-chevron-circle-up' => esc_html__( 'Chevron Circle Up', 'flipmart' ),
        'fa-chevron-down' => esc_html__( 'Chevron Down', 'flipmart' ),
        'fa-chevron-left' => esc_html__( 'Chevron Left', 'flipmart' ),
        'fa-chevron-right' => esc_html__( 'Chevron Right', 'flipmart' ),
        'fa-chevron-up' => esc_html__( 'Chevron Up', 'flipmart' ),
        'fa-child' => esc_html__( 'Child', 'flipmart' ),
        'fa-circle-o-notch' => esc_html__( 'Circle Outline Notch', 'flipmart' ),
        'fa-circle-o' => esc_html__( 'Circle Outline', 'flipmart' ),
        'fa-circle-thin' => esc_html__( 'Circle Thin', 'flipmart' ),
        'fa-circle' => esc_html__( 'Circle', 'flipmart' ),
        'fa-clipboard' => esc_html__( 'Clipboard', 'flipmart' ),
        'fa-clock-o' => esc_html__( 'Clock Outline', 'flipmart' ),
        'fa-close' => esc_html__( 'Close', 'flipmart' ),
        'fa-cloud-download' => esc_html__( 'Cloud Download', 'flipmart' ),
        'fa-cloud-upload' => esc_html__( 'Cloud Upload', 'flipmart' ),
        'fa-cloud' => esc_html__( 'Cloud', 'flipmart' ),
        'fa-cny' => esc_html__( 'Cny', 'flipmart' ),
        'fa-code-fork' => esc_html__( 'Code Fork', 'flipmart' ),
        'fa-code' => esc_html__( 'Code', 'flipmart' ),
        'fa-codepen' => esc_html__( 'Codepen', 'flipmart' ),
        'fa-coffee' => esc_html__( 'Coffee', 'flipmart' ),
        'fa-cog' => esc_html__( 'Cog', 'flipmart' ),
        'fa-cogs' => esc_html__( 'Cogs', 'flipmart' ),
        'fa-columns' => esc_html__( 'Columns', 'flipmart' ),
        'fa-comment-o' => esc_html__( 'Comment Outline', 'flipmart' ),
        'fa-comment' => esc_html__( 'Comment', 'flipmart' ),
        'fa-comments-o' => esc_html__( 'Comments Outline', 'flipmart' ),
        'fa-comments' => esc_html__( 'Comments', 'flipmart' ),
        'fa-compass' => esc_html__( 'Compass', 'flipmart' ),
        'fa-compress' => esc_html__( 'Compress', 'flipmart' ),
        'fa-copy' => esc_html__( 'Copy', 'flipmart' ),
        'fa-copyright' => esc_html__( 'Copyright', 'flipmart' ),
        'fa-credit-card' => esc_html__( 'Credit Card', 'flipmart' ),
        'fa-crop' => esc_html__( 'Crop', 'flipmart' ),
        'fa-crosshairs' => esc_html__( 'Crosshairs', 'flipmart' ),
        'fa-css3' => esc_html__( 'Css3', 'flipmart' ),
        'fa-cube' => esc_html__( 'Cube', 'flipmart' ),
        'fa-cubes' => esc_html__( 'Cubes', 'flipmart' ),
        'fa-cut' => esc_html__( 'Cut', 'flipmart' ),
        'fa-cutlery' => esc_html__( 'Cutlery', 'flipmart' ),
        'fa-dashboard' => esc_html__( 'Dashboard', 'flipmart' ),
        'fa-database' => esc_html__( 'Database', 'flipmart' ),
        'fa-dedent' => esc_html__( 'Dedent', 'flipmart' ),
        'fa-delicious' => esc_html__( 'Delicious', 'flipmart' ),
        'fa-desktop' => esc_html__( 'Desktop', 'flipmart' ),
        'fa-deviantart' => esc_html__( 'Deviantart', 'flipmart' ),
        'fa-digg' => esc_html__( 'Digg', 'flipmart' ),
        'fa-diamond' => esc_html__( 'Diamond', 'flipmart' ),
        'fa-dollar' => esc_html__( 'Dollar', 'flipmart' ),
        'fa-dot-circle-o' => esc_html__( 'Dot Circle Outline', 'flipmart' ),
        'fa-download' => esc_html__( 'Download', 'flipmart' ),
        'fa-dribbble' => esc_html__( 'Dribbble', 'flipmart' ),
        'fa-dropbox' => esc_html__( 'Dropbox', 'flipmart' ),
        'fa-drupal' => esc_html__( 'Drupal', 'flipmart' ),
        'fa-edit' => esc_html__( 'Edit', 'flipmart' ),
        'fa-eject' => esc_html__( 'Eject', 'flipmart' ),
        'fa-ellipsis-h' => esc_html__( 'Ellipsis H', 'flipmart' ),
        'fa-ellipsis-v' => esc_html__( 'Ellipsis V', 'flipmart' ),
        'fa-empire' => esc_html__( 'Empire', 'flipmart' ),
        'fa-envelope-o' => esc_html__( 'Envelope Outline', 'flipmart' ),
        'fa-envelope-square' => esc_html__( 'Envelope Square', 'flipmart' ),
        'fa-envelope' => esc_html__( 'Envelope', 'flipmart' ),
        'fa-envira' => esc_html__( 'Envira', 'flipmart' ),
        'fa-eraser' => esc_html__( 'Eraser', 'flipmart' ),
        'fa-eur' => esc_html__( 'Eur', 'flipmart' ),
        'fa-euro' => esc_html__( 'Euro', 'flipmart' ),
        'fa-exchange' => esc_html__( 'Exchange', 'flipmart' ),
        'fa-exclamation-circle' => esc_html__( 'Exclamation Circle', 'flipmart' ),
        'fa-exclamation-triangle' => esc_html__( 'Exclamation Triangle', 'flipmart' ),
        'fa-exclamation' => esc_html__( 'Exclamation', 'flipmart' ),
        'fa-expand' => esc_html__( 'Expand', 'flipmart' ),
        'fa-external-link-square' => esc_html__( 'External Link Square', 'flipmart' ),
        'fa-external-link' => esc_html__( 'External Link', 'flipmart' ),
        'fa-eye-slash' => esc_html__( 'Eye Slash', 'flipmart' ),
        'fa-eye' => esc_html__( 'Eye', 'flipmart' ),
        'fa-eyedropper' => esc_html__( 'Eyedropper', 'flipmart' ),
        'fa-facebook-square' => esc_html__( 'Facebook Square', 'flipmart' ),
        'fa-facebook' => esc_html__( 'Facebook', 'flipmart' ),
        'fa-fast-backward' => esc_html__( 'Fast Backward', 'flipmart' ),
        'fa-fast-forward' => esc_html__( 'Fast Forward', 'flipmart' ),
        'fa-fax' => esc_html__( 'Fax', 'flipmart' ),
        'fa-female' => esc_html__( 'Female', 'flipmart' ),
        'fa-fighter-jet' => esc_html__( 'Fighter Jet', 'flipmart' ),
        'fa-file-archive-o' => esc_html__( 'File Archive Outline', 'flipmart' ),
        'fa-file-audio-o' => esc_html__( 'File Audio Outline', 'flipmart' ),
        'fa-file-code-o' => esc_html__( 'File Code Outline', 'flipmart' ),
        'fa-file-excel-o' => esc_html__( 'File Excel Outline', 'flipmart' ),
        'fa-file-image-o' => esc_html__( 'File Image Outline', 'flipmart' ),
        'fa-file-movie-o' => esc_html__( 'File Movie Outline', 'flipmart' ),
        'fa-file-o' => esc_html__( 'File Outline', 'flipmart' ),
        'fa-file-pdf-o' => esc_html__( 'File Pdf Outline', 'flipmart' ),
        'fa-file-photo-o' => esc_html__( 'File Photo Outline', 'flipmart' ),
        'fa-file-picture-o' => esc_html__( 'File Picture Outline', 'flipmart' ),
        'fa-file-powerpoint-o' => esc_html__( 'File Powerpoint Outline', 'flipmart' ),
        'fa-file-sound-o' => esc_html__( 'File Sound Outline', 'flipmart' ),
        'fa-file-text-o' => esc_html__( 'File Text Outline', 'flipmart' ),
        'fa-file-text' => esc_html__( 'File Text', 'flipmart' ),
        'fa-file-video-o' => esc_html__( 'File Video Outline', 'flipmart' ),
        'fa-file-word-o' => esc_html__( 'File Word Outline', 'flipmart' ),
        'fa-file-zip-o' => esc_html__( 'File Zip Outline', 'flipmart' ),
        'fa-file' => esc_html__( 'File', 'flipmart' ),
        'fa-files-o' => esc_html__( 'Files Outline', 'flipmart' ),
        'fa-film' => esc_html__( 'Film', 'flipmart' ),
        'fa-filter' => esc_html__( 'Filter', 'flipmart' ),
        'fa-fire-extinguisher' => esc_html__( 'Fire Extinguisher', 'flipmart' ),
        'fa-fire' => esc_html__( 'Fire', 'flipmart' ),
        'fa-flag-checkered' => esc_html__( 'Flag Checkered', 'flipmart' ),
        'fa-flag-o' => esc_html__( 'Flag Outline', 'flipmart' ),
        'fa-flag' => esc_html__( 'Flag', 'flipmart' ),
        'fa-flash' => esc_html__( 'Flash', 'flipmart' ),
        'fa-flask' => esc_html__( 'Flask', 'flipmart' ),
        'fa-flickr' => esc_html__( 'Flickr', 'flipmart' ),
        'fa-floppy-o' => esc_html__( 'Floppy Outline', 'flipmart' ),
        'fa-folder-o' => esc_html__( 'Folder Outline', 'flipmart' ),
        'fa-folder-open-o' => esc_html__( 'Folder Outlinepen Outline', 'flipmart' ),
        'fa-folder-open' => esc_html__( 'Folder Outlinepen', 'flipmart' ),
        'fa-folder' => esc_html__( 'Folder', 'flipmart' ),
        'fa-font' => esc_html__( 'Font', 'flipmart' ),
        'fa-forward' => esc_html__( 'Forward', 'flipmart' ),
        'fa-foursquare' => esc_html__( 'Foursquare', 'flipmart' ),
        'fa-frown-o' => esc_html__( 'Frown Outline', 'flipmart' ),
        'fa-futbol-o' => esc_html__( 'Futbol Outline', 'flipmart' ),
        'fa-gamepad' => esc_html__( 'Gamepad', 'flipmart' ),
        'fa-gavel' => esc_html__( 'Gavel', 'flipmart' ),
        'fa-gbp' => esc_html__( 'Gbp', 'flipmart' ),
        'fa-ge' => esc_html__( 'Ge', 'flipmart' ),
        'fa-gear' => esc_html__( 'Gear', 'flipmart' ),
        'fa-gears' => esc_html__( 'Gears', 'flipmart' ),
        'fa-gift' => esc_html__( 'Gift', 'flipmart' ),
        'fa-git-square' => esc_html__( 'Git Square', 'flipmart' ),
        'fa-git' => esc_html__( 'Git', 'flipmart' ),
        'fa-github-alt' => esc_html__( 'Github Alt', 'flipmart' ),
        'fa-github-square' => esc_html__( 'Github Square', 'flipmart' ),
        'fa-github' => esc_html__( 'Github', 'flipmart' ),
        'fa-gittip' => esc_html__( 'Gittip', 'flipmart' ),
        'fa-glass' => esc_html__( 'Glass', 'flipmart' ),
        'fa-globe' => esc_html__( 'Globe', 'flipmart' ),
        'fa-google-plus-square' => esc_html__( 'Google Plus Square', 'flipmart' ),
        'fa-google-plus' => esc_html__( 'Google Plus', 'flipmart' ),
        'fa-google-wallet' => esc_html__( 'Google Wallet', 'flipmart' ),
        'fa-google' => esc_html__( 'Google', 'flipmart' ),
        'fa-graduation-cap' => esc_html__( 'Graduation Cap', 'flipmart' ),
        'fa-group' => esc_html__( 'Group', 'flipmart' ),
        'fa-h-square' => esc_html__( 'H Square', 'flipmart' ),
        'fa-hacker-news' => esc_html__( 'Hacker News', 'flipmart' ),
        'fa-hand-o-down' => esc_html__( 'Hand Outline Down', 'flipmart' ),
        'fa-hand-o-left' => esc_html__( 'Hand Outline Left', 'flipmart' ),
        'fa-hand-o-right' => esc_html__( 'Hand Outline Right', 'flipmart' ),
        'fa-hand-o-up' => esc_html__( 'Hand Outline Up', 'flipmart' ),
        'fa-hdd-o' => esc_html__( 'Hdd Outline', 'flipmart' ),
        'fa-header' => esc_html__( 'Header', 'flipmart' ),
        'fa-headphones' => esc_html__( 'Headphones', 'flipmart' ),
        'fa-heart-o' => esc_html__( 'Heart Outline', 'flipmart' ),
        'fa-heart' => esc_html__( 'Heart', 'flipmart' ),
        'fa-heartbeat' => esc_html__( 'Heart Beat', 'flipmart' ),
        'fa-history' => esc_html__( 'History', 'flipmart' ),
        'fa-home' => esc_html__( 'Home', 'flipmart' ),
        'fa-hospital-o' => esc_html__( 'Hospital Outline', 'flipmart' ),
        'fa-html5' => esc_html__( 'Html5', 'flipmart' ),
        'fa-ils' => esc_html__( 'Ils', 'flipmart' ),
        'fa-image' => esc_html__( 'Image', 'flipmart' ),
        'fa-inbox' => esc_html__( 'Inbox', 'flipmart' ),
        'fa-indent' => esc_html__( 'Indent', 'flipmart' ),
        'fa-info-circle' => esc_html__( 'Info Circle', 'flipmart' ),
        'fa-info' => esc_html__( 'Info', 'flipmart' ),
        'fa-inr' => esc_html__( 'Inr', 'flipmart' ),
        'fa-instagram' => esc_html__( 'Instagram', 'flipmart' ),
        'fa-institution' => esc_html__( 'Institution', 'flipmart' ),
        'fa-ioxhost' => esc_html__( 'Ioxhost', 'flipmart' ),
        'fa-italic' => esc_html__( 'Italic', 'flipmart' ),
        'fa-joomla' => esc_html__( 'Joomla', 'flipmart' ),
        'fa-jpy' => esc_html__( 'Jpy', 'flipmart' ),
        'fa-jsfiddle' => esc_html__( 'Jsfiddle', 'flipmart' ),
        'fa-key' => esc_html__( 'Key', 'flipmart' ),
        'fa-keyboard-o' => esc_html__( 'Keyboard Outline', 'flipmart' ),
        'fa-krw' => esc_html__( 'Krw', 'flipmart' ),
        'fa-language' => esc_html__( 'Language', 'flipmart' ),
        'fa-laptop' => esc_html__( 'Laptop', 'flipmart' ),
        'fa-lastfm-square' => esc_html__( 'Lastfm Square', 'flipmart' ),
        'fa-lastfm' => esc_html__( 'Lastfm', 'flipmart' ),
        'fa-leaf' => esc_html__( 'Leaf', 'flipmart' ),
        'fa-legal' => esc_html__( 'Legal', 'flipmart' ),
        'fa-lemon-o' => esc_html__( 'Lemon Outline', 'flipmart' ),
        'fa-level-down' => esc_html__( 'Level Down', 'flipmart' ),
        'fa-level-up' => esc_html__( 'Level Up', 'flipmart' ),
        'fa-life-bouy' => esc_html__( 'Life Bouy', 'flipmart' ),
        'fa-life-buoy' => esc_html__( 'Life Buoy', 'flipmart' ),
        'fa-life-ring' => esc_html__( 'Life Ring', 'flipmart' ),
        'fa-life-saver' => esc_html__( 'Life Saver', 'flipmart' ),
        'fa-lightbulb-o' => esc_html__( 'Lightbulb Outline', 'flipmart' ),
        'fa-line-chart' => esc_html__( 'Line Chart', 'flipmart' ),
        'fa-link' => esc_html__( 'Link', 'flipmart' ),
        'fa-linkedin-square' => esc_html__( 'Linkedin Square', 'flipmart' ),
        'fa-linkedin' => esc_html__( 'Linkedin', 'flipmart' ),
        'fa-linux' => esc_html__( 'Linux', 'flipmart' ),
        'fa-list-alt' => esc_html__( 'List Alt', 'flipmart' ),
        'fa-list-ol' => esc_html__( 'List Outlinel', 'flipmart' ),
        'fa-list-ul' => esc_html__( 'List Ul', 'flipmart' ),
        'fa-list' => esc_html__( 'List', 'flipmart' ),
        'fa-location-arrow' => esc_html__( 'Location Arrow', 'flipmart' ),
        'fa-lock' => esc_html__( 'Lock', 'flipmart' ),
        'fa-long-arrow-down' => esc_html__( 'Long Arrow Down', 'flipmart' ),
        'fa-long-arrow-left' => esc_html__( 'Long Arrow Left', 'flipmart' ),
        'fa-long-arrow-right' => esc_html__( 'Long Arrow Right', 'flipmart' ),
        'fa-long-arrow-up' => esc_html__( 'Long Arrow Up', 'flipmart' ),
        'fa-magic' => esc_html__( 'Magic', 'flipmart' ),
        'fa-magnet' => esc_html__( 'Magnet', 'flipmart' ),
        'fa-mail-forward' => esc_html__( 'Mail Forward', 'flipmart' ),
        'fa-mail-reply-all' => esc_html__( 'Mail Reply All', 'flipmart' ),
        'fa-mail-reply' => esc_html__( 'Mail Reply', 'flipmart' ),
        'fa-male' => esc_html__( 'Male', 'flipmart' ),
        'fa-map-marker' => esc_html__( 'Map Marker', 'flipmart' ),
        'fa-maxcdn' => esc_html__( 'Maxcdn', 'flipmart' ),
        'fa-meanpath' => esc_html__( 'Meanpath', 'flipmart' ),
        'fa-medkit' => esc_html__( 'Medkit', 'flipmart' ),
        'fa-meh-o' => esc_html__( 'Meh Outline', 'flipmart' ),
        'fa-microphone-slash' => esc_html__( 'Microphone Slash', 'flipmart' ),
        'fa-microphone' => esc_html__( 'Microphone', 'flipmart' ),
        'fa-minus-circle' => esc_html__( 'Minus Circle', 'flipmart' ),
        'fa-minus-square-o' => esc_html__( 'Minus Square Outline', 'flipmart' ),
        'fa-minus-square' => esc_html__( 'Minus Square', 'flipmart' ),
        'fa-minus' => esc_html__( 'Minus', 'flipmart' ),
        'fa-mobile-phone' => esc_html__( 'Mobile Phone', 'flipmart' ),
        'fa-mobile' => esc_html__( 'Mobile', 'flipmart' ),
        'fa-money' => esc_html__( 'Money', 'flipmart' ),
        'fa-moon-o' => esc_html__( 'Moon Outline', 'flipmart' ),
        'fa-mortar-board' => esc_html__( 'Mortar Board', 'flipmart' ),
        'fa-music' => esc_html__( 'Music', 'flipmart' ),
        'fa-navicon' => esc_html__( 'Navicon', 'flipmart' ),
        'fa-newspaper-o' => esc_html__( 'Newspaper Outline', 'flipmart' ),
        'fa-openid' => esc_html__( 'Openid', 'flipmart' ),
        'fa-outdent' => esc_html__( 'Outdent', 'flipmart' ),
        'fa-pagelines' => esc_html__( 'Pagelines', 'flipmart' ),
        'fa-paint-brush' => esc_html__( 'Paint Brush', 'flipmart' ),
        'fa-paper-plane-o' => esc_html__( 'Paper Plane Outline', 'flipmart' ),
        'fa-paper-plane' => esc_html__( 'Paper Plane', 'flipmart' ),
        'fa-paperclip' => esc_html__( 'Paperclip', 'flipmart' ),
        'fa-paragraph' => esc_html__( 'Paragraph', 'flipmart' ),
        'fa-paste' => esc_html__( 'Paste', 'flipmart' ),
        'fa-pause' => esc_html__( 'Pause', 'flipmart' ),
        'fa-paw' => esc_html__( 'Paw', 'flipmart' ),
        'fa-paypal' => esc_html__( 'Paypal', 'flipmart' ),
        'fa-pencil-square-o' => esc_html__( 'Pencil Square Outline', 'flipmart' ),
        'fa-pencil-square' => esc_html__( 'Pencil Square', 'flipmart' ),
        'fa-pencil' => esc_html__( 'Pencil', 'flipmart' ),
        'fa-phone-square' => esc_html__( 'Phone Square', 'flipmart' ),
        'fa-phone' => esc_html__( 'Phone', 'flipmart' ),
        'fa-photo' => esc_html__( 'Photo', 'flipmart' ),
        'fa-picture-o' => esc_html__( 'Picture Outline', 'flipmart' ),
        'fa-pie-chart' => esc_html__( 'Pie Chart', 'flipmart' ),
        'fa-pied-piper-alt' => esc_html__( 'Pied Piper Alt', 'flipmart' ),
        'fa-pied-piper' => esc_html__( 'Pied Piper', 'flipmart' ),
        'fa-pinterest-square' => esc_html__( 'Pinterest Square', 'flipmart' ),
        'fa-pinterest' => esc_html__( 'Pinterest', 'flipmart' ),
        'fa-plane' => esc_html__( 'Plane', 'flipmart' ),
        'fa-play-circle-o' => esc_html__( 'Play Circle Outline', 'flipmart' ),
        'fa-play-circle' => esc_html__( 'Play Circle', 'flipmart' ),
        'fa-play' => esc_html__( 'Play', 'flipmart' ),
        'fa-plug' => esc_html__( 'Plug', 'flipmart' ),
        'fa-plus-circle' => esc_html__( 'Plus Circle', 'flipmart' ),
        'fa-plus-square-o' => esc_html__( 'Plus Square Outline', 'flipmart' ),
        'fa-plus-square' => esc_html__( 'Plus Square', 'flipmart' ),
        'fa-plus' => esc_html__( 'Plus', 'flipmart' ),
        'fa-power-off' => esc_html__( 'Power Outlineff', 'flipmart' ),
        'fa-print' => esc_html__( 'Print', 'flipmart' ),
        'fa-puzzle-piece' => esc_html__( 'Puzzle Piece', 'flipmart' ),
        'fa-qq' => esc_html__( 'Qq', 'flipmart' ),
        'fa-qrcode' => esc_html__( 'Qrcode', 'flipmart' ),
        'fa-question-circle' => esc_html__( 'Question Circle', 'flipmart' ),
        'fa-question' => esc_html__( 'Question', 'flipmart' ),
        'fa-quote-left' => esc_html__( 'Quote Left', 'flipmart' ),
        'fa-quote-right' => esc_html__( 'Quote Right', 'flipmart' ),
        'fa-ra' => esc_html__( 'Ra', 'flipmart' ),
        'fa-random' => esc_html__( 'Random', 'flipmart' ),
        'fa-rebel' => esc_html__( 'Rebel', 'flipmart' ),
        'fa-recycle' => esc_html__( 'Recycle', 'flipmart' ),
        'fa-reddit-square' => esc_html__( 'Reddit Square', 'flipmart' ),
        'fa-reddit' => esc_html__( 'Reddit', 'flipmart' ),
        'fa-refresh' => esc_html__( 'Refresh', 'flipmart' ),
        'fa-remove' => esc_html__( 'Remove', 'flipmart' ),
        'fa-renren' => esc_html__( 'Renren', 'flipmart' ),
        'fa-reorder' => esc_html__( 'Reorder', 'flipmart' ),
        'fa-repeat' => esc_html__( 'Repeat', 'flipmart' ),
        'fa-reply-all' => esc_html__( 'Reply All', 'flipmart' ),
        'fa-reply' => esc_html__( 'Reply', 'flipmart' ),
        'fa-retweet' => esc_html__( 'Retweet', 'flipmart' ),
        'fa-rmb' => esc_html__( 'Rmb', 'flipmart' ),
        'fa-road' => esc_html__( 'Road', 'flipmart' ),
        'fa-rocket' => esc_html__( 'Rocket', 'flipmart' ),
        'fa-rotate-left' => esc_html__( 'Rotate Left', 'flipmart' ),
        'fa-rotate-right' => esc_html__( 'Rotate Right', 'flipmart' ),
        'fa-rouble' => esc_html__( 'Rouble', 'flipmart' ),
        'fa-rss-square' => esc_html__( 'Rss Square', 'flipmart' ),
        'fa-rss' => esc_html__( 'Rss', 'flipmart' ),
        'fa-rub' => esc_html__( 'Rub', 'flipmart' ),
        'fa-ruble' => esc_html__( 'Ruble', 'flipmart' ),
        'fa-rupee' => esc_html__( 'Rupee', 'flipmart' ),
        'fa-save' => esc_html__( 'Save', 'flipmart' ),
        'fa-scissors' => esc_html__( 'Scissors', 'flipmart' ),
        'fa-search-minus' => esc_html__( 'Search Minus', 'flipmart' ),
        'fa-search-plus' => esc_html__( 'Search Plus', 'flipmart' ),
        'fa-search' => esc_html__( 'Search', 'flipmart' ),
        'fa-send-o' => esc_html__( 'Send Outline', 'flipmart' ),
        'fa-send' => esc_html__( 'Send', 'flipmart' ),
        'fa-share-alt-square' => esc_html__( 'Share Alt Square', 'flipmart' ),
        'fa-share-alt' => esc_html__( 'Share Alt', 'flipmart' ),
        'fa-share-square-o' => esc_html__( 'Share Square Outline', 'flipmart' ),
        'fa-share-square' => esc_html__( 'Share Square', 'flipmart' ),
        'fa-share' => esc_html__( 'Share', 'flipmart' ),
        'fa-shekel' => esc_html__( 'Shekel', 'flipmart' ),
        'fa-sheqel' => esc_html__( 'Sheqel', 'flipmart' ),
        'fa-shield' => esc_html__( 'Shield', 'flipmart' ),
        'fa-shopping-cart' => esc_html__( 'Shopping Cart', 'flipmart' ),
        'fa-shopping-bag' => esc_html__( 'Shopping Bag', 'flipmart' ),
        'fa-sign-in' => esc_html__( 'Sign In', 'flipmart' ),
        'fa-sign-out' => esc_html__( 'Sign Outlineut', 'flipmart' ),
        'fa-signal' => esc_html__( 'Signal', 'flipmart' ),
        'fa-sitemap' => esc_html__( 'Sitemap', 'flipmart' ),
        'fa-skype' => esc_html__( 'Skype', 'flipmart' ),
        'fa-slack' => esc_html__( 'Slack', 'flipmart' ),
        'fa-sliders' => esc_html__( 'Sliders', 'flipmart' ),
        'fa-slideshare' => esc_html__( 'Slideshare', 'flipmart' ),
        'fa-smile-o' => esc_html__( 'Smile Outline', 'flipmart' ),
        'fa-soccer-ball-o' => esc_html__( 'Soccer Ball Outline', 'flipmart' ),
        'fa-sort-alpha-asc' => esc_html__( 'Sort Alpha Asc', 'flipmart' ),
        'fa-sort-alpha-desc' => esc_html__( 'Sort Alpha Desc', 'flipmart' ),
        'fa-sort-amount-asc' => esc_html__( 'Sort Amount Asc', 'flipmart' ),
        'fa-sort-amount-desc' => esc_html__( 'Sort Amount Desc', 'flipmart' ),
        'fa-sort-asc' => esc_html__( 'Sort Asc', 'flipmart' ),
        'fa-sort-desc' => esc_html__( 'Sort Desc', 'flipmart' ),
        'fa-sort-down' => esc_html__( 'Sort Down', 'flipmart' ),
        'fa-sort-numeric-asc' => esc_html__( 'Sort Numeric Asc', 'flipmart' ),
        'fa-sort-numeric-desc' => esc_html__( 'Sort Numeric Desc', 'flipmart' ),
        'fa-sort-up' => esc_html__( 'Sort Up', 'flipmart' ),
        'fa-sort' => esc_html__( 'Sort', 'flipmart' ),
        'fa-soundcloud' => esc_html__( 'Soundcloud', 'flipmart' ),
        'fa-space-shuttle' => esc_html__( 'Space Shuttle', 'flipmart' ),
        'fa-spinner' => esc_html__( 'Spinner', 'flipmart' ),
        'fa-spoon' => esc_html__( 'Spoon', 'flipmart' ),
        'fa-spotify' => esc_html__( 'Spotify', 'flipmart' ),
        'fa-square-o' => esc_html__( 'Square Outline', 'flipmart' ),
        'fa-square' => esc_html__( 'Square', 'flipmart' ),
        'fa-stack-exchange' => esc_html__( 'Stack Exchange', 'flipmart' ),
        'fa-stack-overflow' => esc_html__( 'Stack Outlineverflow', 'flipmart' ),
        'fa-star-half-empty' => esc_html__( 'Star Half Empty', 'flipmart' ),
        'fa-star-half-full' => esc_html__( 'Star Half Full', 'flipmart' ),
        'fa-star-half-o' => esc_html__( 'Star Half Outline', 'flipmart' ),
        'fa-star-half' => esc_html__( 'Star Half', 'flipmart' ),
        'fa-star-o' => esc_html__( 'Star Outline', 'flipmart' ),
        'fa-star' => esc_html__( 'Star', 'flipmart' ),
        'fa-steam-square' => esc_html__( 'Steam Square', 'flipmart' ),
        'fa-steam' => esc_html__( 'Steam', 'flipmart' ),
        'fa-step-backward' => esc_html__( 'Step Backward', 'flipmart' ),
        'fa-step-forward' => esc_html__( 'Step Forward', 'flipmart' ),
        'fa-stethoscope' => esc_html__( 'Stethoscope', 'flipmart' ),
        'fa-stop' => esc_html__( 'Stop', 'flipmart' ),
        'fa-strikethrough' => esc_html__( 'Strikethrough', 'flipmart' ),
        'fa-stumbleupon-circle' => esc_html__( 'Stumbleupon Circle', 'flipmart' ),
        'fa-stumbleupon' => esc_html__( 'Stumbleupon', 'flipmart' ),
        'fa-subscript' => esc_html__( 'Subscript', 'flipmart' ),
        'fa-suitcase' => esc_html__( 'Suitcase', 'flipmart' ),
        'fa-sun-o' => esc_html__( 'Sun Outline', 'flipmart' ),
        'fa-superscript' => esc_html__( 'Superscript', 'flipmart' ),
        'fa-support' => esc_html__( 'Support', 'flipmart' ),
        'fa-table' => esc_html__( 'Table', 'flipmart' ),
        'fa-tablet' => esc_html__( 'Tablet', 'flipmart' ),
        'fa-tachometer' => esc_html__( 'Tachometer', 'flipmart' ),
        'fa-tag' => esc_html__( 'Tag', 'flipmart' ),
        'fa-tags' => esc_html__( 'Tags', 'flipmart' ),
        'fa-tasks' => esc_html__( 'Tasks', 'flipmart' ),
        'fa-taxi' => esc_html__( 'Taxi', 'flipmart' ),
        'fa-tencent-weibo' => esc_html__( 'Tencent Weibo', 'flipmart' ),
        'fa-terminal' => esc_html__( 'Terminal', 'flipmart' ),
        'fa-text-height' => esc_html__( 'Text Height', 'flipmart' ),
        'fa-text-width' => esc_html__( 'Text Width', 'flipmart' ),
        'fa-th-large' => esc_html__( 'Th Large', 'flipmart' ),
        'fa-th-list' => esc_html__( 'Th List', 'flipmart' ),
        'fa-th' => esc_html__( 'Th', 'flipmart' ),
        'fa-thumb-tack' => esc_html__( 'Thumb Tack', 'flipmart' ),
        'fa-thumbs-down' => esc_html__( 'Thumbs Down', 'flipmart' ),
        'fa-thumbs-o-down' => esc_html__( 'Thumbs Outline Down', 'flipmart' ),
        'fa-thumbs-o-up' => esc_html__( 'Thumbs Outline Up', 'flipmart' ),
        'fa-thumbs-up' => esc_html__( 'Thumbs Up', 'flipmart' ),
        'fa-ticket' => esc_html__( 'Ticket', 'flipmart' ),
        'fa-times-circle-o' => esc_html__( 'Times Circle Outline', 'flipmart' ),
        'fa-times-circle' => esc_html__( 'Times Circle', 'flipmart' ),
        'fa-times' => esc_html__( 'Times', 'flipmart' ),
        'fa-tint' => esc_html__( 'Tint', 'flipmart' ),
        'fa-toggle-down' => esc_html__( 'Toggle Down', 'flipmart' ),
        'fa-toggle-left' => esc_html__( 'Toggle Left', 'flipmart' ),
        'fa-toggle-off' => esc_html__( 'Toggle Outlineff', 'flipmart' ),
        'fa-toggle-on' => esc_html__( 'Toggle Outlinen', 'flipmart' ),
        'fa-toggle-right' => esc_html__( 'Toggle Right', 'flipmart' ),
        'fa-toggle-up' => esc_html__( 'Toggle Up', 'flipmart' ),
        'fa-trash-o' => esc_html__( 'Trash Outline', 'flipmart' ),
        'fa-trash' => esc_html__( 'Trash', 'flipmart' ),
        'fa-tree' => esc_html__( 'Tree', 'flipmart' ),
        'fa-trello' => esc_html__( 'Trello', 'flipmart' ),
        'fa-trophy' => esc_html__( 'Trophy', 'flipmart' ),
        'fa-truck' => esc_html__( 'Truck', 'flipmart' ),
        'fa-try' => esc_html__( 'Try', 'flipmart' ),
        'fa-tty' => esc_html__( 'Tty', 'flipmart' ),
        'fa-tumblr-square' => esc_html__( 'Tumblr Square', 'flipmart' ),
        'fa-tumblr' => esc_html__( 'Tumblr', 'flipmart' ),
        'fa-turkish-lira' => esc_html__( 'Turkish Lira', 'flipmart' ),
        'fa-twitch' => esc_html__( 'Twitch', 'flipmart' ),
        'fa-twitter-square' => esc_html__( 'Twitter Square', 'flipmart' ),
        'fa-twitter' => esc_html__( 'Twitter', 'flipmart' ),
        'fa-umbrella' => esc_html__( 'Umbrella', 'flipmart' ),
        'fa-underline' => esc_html__( 'Underline', 'flipmart' ),
        'fa-undo' => esc_html__( 'Undo', 'flipmart' ),
        'fa-university' => esc_html__( 'University', 'flipmart' ),
        'fa-unlink' => esc_html__( 'Unlink', 'flipmart' ),
        'fa-unlock-alt' => esc_html__( 'Unlock Alt', 'flipmart' ),
        'fa-unlock' => esc_html__( 'Unlock', 'flipmart' ),
        'fa-unsorted' => esc_html__( 'Unsorted', 'flipmart' ),
        'fa-upload' => esc_html__( 'Upload', 'flipmart' ),
        'fa-usd' => esc_html__( 'Usd', 'flipmart' ),
        'fa-user-md' => esc_html__( 'User Md', 'flipmart' ),
        'fa-user' => esc_html__( 'User', 'flipmart' ),
        'fa-users' => esc_html__( 'Users', 'flipmart' ),
        'fa-video-camera' => esc_html__( 'Video Camera', 'flipmart' ),
        'fa-vimeo-square' => esc_html__( 'Vimeo Square', 'flipmart' ),
        'fa-vine' => esc_html__( 'Vine', 'flipmart' ),
        'fa-vk' => esc_html__( 'Vk', 'flipmart' ),
        'fa-volume-down' => esc_html__( 'Volume Down', 'flipmart' ),
        'fa-volume-off' => esc_html__( 'Volume Outlineff', 'flipmart' ),
        'fa-volume-up' => esc_html__( 'Volume Up', 'flipmart' ),
        'fa-warning' => esc_html__( 'Warning', 'flipmart' ),
        'fa-wechat' => esc_html__( 'Wechat', 'flipmart' ),
        'fa-weibo' => esc_html__( 'Weibo', 'flipmart' ),
        'fa-weixin' => esc_html__( 'Weixin', 'flipmart' ),
        'fa-wheelchair' => esc_html__( 'Wheelchair', 'flipmart' ),
        'fa-wifi' => esc_html__( 'Wifi', 'flipmart' ),
        'fa-windows' => esc_html__( 'Windows', 'flipmart' ),
        'fa-won' => esc_html__( 'Won', 'flipmart' ),
        'fa-wordpress' => esc_html__( 'WordPress', 'flipmart' ),
        'fa-wrench' => esc_html__( 'Wrench', 'flipmart' ),
        'fa-xing-square' => esc_html__( 'Xing Square', 'flipmart' ),
        'fa-xing' => esc_html__( 'Xing', 'flipmart' ),
        'fa-yahoo' => esc_html__( 'Yahoo', 'flipmart' ),
        'fa-yelp' => esc_html__( 'Yelp', 'flipmart' ),
        'fa-yen' => esc_html__( 'Yen', 'flipmart' ),
        'fa-youtube-play' => esc_html__( 'Youtube Play', 'flipmart' ),
        'fa-youtube-square' => esc_html__( 'Youtube Square', 'flipmart' ),
        'fa-youtube' => esc_html__( 'Youtube', 'flipmart' )
     );
}

/**
 * [yog_get_theme_animations description]
 * @method yog_get_theme_animations
 * @param  [type]                $attributes [description]
 * @return [type]                            [description]
 */
function yog_get_theme_animations() {
    return array( 
		esc_html__('No Animation','flipmart') => '',
        esc_html__('Bounce','flipmart') => 'bounce',
        esc_html__('Bounce In','flipmart') => 'bounceIn',
        esc_html__('Bounce In Up','flipmart') => 'bounceInUp',
        esc_html__('Bounce In Down','flipmart') => 'bounceInDown',
        esc_html__('Bounce In Left','flipmart') => 'bounceInLeft',
        esc_html__('Bounce In Right','flipmart') => 'bounceInRight',
        esc_html__('Fade In','flipmart') => 'fadeIn',
        esc_html__('Fade In Up','flipmart') => 'fadeInUp',
        esc_html__('Fade In Down','flipmart') => 'fadeInDown',
        esc_html__('Fade In Left','flipmart') => 'fadeInLeft',
        esc_html__('Fade In Right','flipmart') => 'fadeInRight',
        esc_html__('Fade In Up Big','flipmart') => 'fadeInUpBig',
        esc_html__('Fade In Down Big','flipmart') => 'fadeInDownBig',
        esc_html__('Fade In Left Big','flipmart') => 'fadeInLeftBig',
        esc_html__('Fade In Right Big','flipmart') => 'fadeInRightBig',
		esc_html__('Flash','flipmart') => 'flash',
        esc_html__('Flip In X','flipmart') => 'flipInX',
        esc_html__('Flip In Y','flipmart') => 'flipInY',
        esc_html__('Jello','flipmart') => 'jello',
        esc_html__('Pulse','flipmart') => 'pulse',
		esc_html__('Shake','flipmart') => 'shake',
		esc_html__('Swing','flipmart') => 'swing',
		esc_html__('Tada','flipmart') => 'tada',
		esc_html__('Rotate In','flipmart') => 'rotateIn',
        esc_html__('Rotate In Up Left','flipmart') => 'rotateInUpLeft',
        esc_html__('Rotate In Down Left','flipmart') => 'rotateInDownLeft',
        esc_html__('Rotate In Up Right','flipmart') => 'rotateInUpRight',
        esc_html__('Rotate In Down Right','flipmart') => 'rotateInDownRight',
        esc_html__('Rubber Band','flipmart') => 'rubberBand',
		esc_html__('Wobble','flipmart') => 'wobble',
		esc_html__('Wiggle','flipmart') => 'wiggle',
        esc_html__('Zoom In','flipmart') => 'zoomIn',
        esc_html__('Zoom In Up','flipmart') => 'zoomInUp',
        esc_html__('Zoom In Down','flipmart') => 'zoomInDown',
        esc_html__('Zoom In Left','flipmart') => 'zoomInLeft',
        esc_html__('Zoom In Right','flipmart') => 'zoomInRight',
        esc_html__('Zoom Out','flipmart') => 'zoomOut',
        esc_html__('Zoom Out Up','flipmart') => 'zoomOutUp',
        esc_html__('Zoom Out Down','flipmart') => 'zoomOutDown',
        esc_html__('Zoom Out Left','flipmart') => 'zoomOutLeft',
        esc_html__('Zoom Out Right','flipmart') => 'zoomOutRight',
    );
}

/**
 * [yog_get_menu_columns description]
 * @method yog_get_menu_columns
 * @param  [type]                $attributes [description]
 * @return [type]                            [description]
 */
function yog_get_menu_columns(){
    return array( 
        'col-xs-12 col-sm-12 col-md-2' => esc_html__( 'Two Column', 'flipmart' ),
        'col-xs-12 col-sm-12 col-md-4' => esc_html__( 'Three Column', 'flipmart' ),
        'col-xs-12 col-sm-12 col-md-3' => esc_html__( 'Four Column', 'flipmart' ),
        'col-xs-12 col-sm-12 col-md-6' => esc_html__( 'Six Column', 'flipmart' )
    );
}